import { Card, CardContent } from "@/components/ui/card";
import CallToAction from "@/components/layout/CallToAction";

export default function AboutSWP() {
  return (
    <div className="bg-neutral-50">
      <div className="container mx-auto px-4 py-12 md:py-16">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold mb-6 text-neutral-800">About Systematic Withdrawal Plan (SWP)</h1>
          
          <div className="space-y-8">
            <Card>
              <CardContent className="p-6">
                <h2 className="text-xl font-bold mb-4 text-primary">What is a Systematic Withdrawal Plan?</h2>
                <p className="text-neutral-600 mb-4">
                  A Systematic Withdrawal Plan (SWP) is a facility that allows an investor to withdraw money from an existing mutual fund at predetermined intervals. It's essentially the opposite of a Systematic Investment Plan (SIP).
                </p>
                <p className="text-neutral-600">
                  SWP provides a regular stream of income to investors while keeping the remaining corpus invested in the market, allowing it to potentially grow over time.
                </p>
              </CardContent>
            </Card>
            
            <Card>
              <CardContent className="p-6">
                <h2 className="text-xl font-bold mb-4 text-primary">How Does SWP Work?</h2>
                <p className="text-neutral-600 mb-4">
                  With an SWP, you start with a lump sum investment in a mutual fund. Then, you set up regular withdrawals (monthly, quarterly, or yearly) based on your income needs.
                </p>
                <p className="text-neutral-600 mb-4">
                  You can choose to withdraw a fixed amount or a fixed percentage of your investment. The remaining balance continues to be invested and can potentially earn returns.
                </p>
                <p className="text-neutral-600">
                  The returns generated by your investment can help offset the withdrawals, allowing your investment to last longer than if you simply withdrew the money without any growth.
                </p>
              </CardContent>
            </Card>
            
            <Card>
              <CardContent className="p-6">
                <h2 className="text-xl font-bold mb-4 text-primary">Benefits of SWP</h2>
                <ul className="list-disc pl-5 space-y-2 text-neutral-600">
                  <li>Regular Income: Provides a steady cash flow at preset intervals</li>
                  <li>Capital Appreciation: Your remaining investment stays in the market with potential for growth</li>
                  <li>Flexibility: You can adjust withdrawal amounts based on your changing needs</li>
                  <li>Tax Efficiency: In many cases, SWP can be more tax-efficient than other income options</li>
                  <li>Inflation Protection: With the right investment strategy, your returns can potentially offset inflation</li>
                  <li>Longevity: Proper planning can help your investment last longer</li>
                </ul>
              </CardContent>
            </Card>
            
            <Card>
              <CardContent className="p-6">
                <h2 className="text-xl font-bold mb-4 text-primary">Who Should Consider SWP?</h2>
                <p className="text-neutral-600 mb-4">
                  SWP is particularly useful for:
                </p>
                <ul className="list-disc pl-5 space-y-2 text-neutral-600">
                  <li>Retirees looking for regular income from their retirement corpus</li>
                  <li>Investors who have accumulated a significant sum and now need regular cash flow</li>
                  <li>People wanting to supplement their existing income</li>
                  <li>Those looking to plan for regular expenses like education fees or EMIs</li>
                </ul>
              </CardContent>
            </Card>
            
            <Card>
              <CardContent className="p-6">
                <h2 className="text-xl font-bold mb-4 text-primary">Things to Consider</h2>
                <p className="text-neutral-600 mb-4">
                  When planning an SWP strategy, it's important to consider:
                </p>
                <ul className="list-disc pl-5 space-y-2 text-neutral-600">
                  <li>Withdrawal Rate: Your withdrawal rate should be sustainable based on expected returns</li>
                  <li>Investment Choice: The underlying investment should match your risk profile and time horizon</li>
                  <li>Inflation Impact: The rising cost of living can affect how long your money lasts</li>
                  <li>Market Volatility: Returns are not guaranteed and will fluctuate with market conditions</li>
                  <li>Tax Implications: Understand the tax treatment of your withdrawals</li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      
      <CallToAction />
    </div>
  );
}
